AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: zzangmin.db_automation.config.ServerlessConfig::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Policies:
          - AWSSecretsManagerGetSecretValuePolicy:
              SecretArn: !Sub arn:aws:secretsmanager:ap-northeast-2:AKIAWI62V3XNN6UEJYXU:secret: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
        Variables:
          SPRING_PROFILES_ACTIVE: develop
          AWS_ACCESS_KEY_ID: AKIAWI62V3XNN6UEJYXU
          AWS_SECRET_ACCESS_KEY: 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

      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'
