# application.properties - References environment variables loaded from .env file

# RDB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.sql.init.mode=never

# Logging - Use environment variables for levels
logging.level.root=${LOGGING_LEVEL_ROOT:info} # Default to info if not set
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_ORG_HIBERNATE_SQL:debug}
logging.level.org.hibernate.type=${LOGGING_LEVEL_ORG_HIBERNATE_TYPE:info}

# Port
server.port=${SERVER_PORT:8080} # Default to 8080 if not set

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Encryption
METADATA_ENCRYPT_KEY=${METADATA_ENCRYPT_KEY}

# Slack
slack.bot-token=${SLACK_BOT_TOKEN}
slack.webbhook-url=${SLACK_WEBHOOK_URL}
slack.app-signing-secret=${SLACK_APP_SIGNING_SECRET}
slack.default-channel-id=${SLACK_DEFAULT_CHANNEL_ID}
slack.verification-token=${SLACK_VERIFICATION_TOKEN}
slack.admin-user-ids=${SLACK_ADMIN_USER_IDS}

